### ISSUE TITLE
project won't install from cargo

### ISSUE THREAD

**Issue by samthurston** [azdle/neo#3]
I apologize, I didn't see an issue template if there is one.

i tried `cargo install neo` and got the following result:

`    Updating crates.io index
  Downloaded neo v0.3.1
  Downloaded 1 crate (7.5 KB) in 0.59s
  Installing neo v0.3.1
error: failed to compile `neo v0.3.1`, intermediate artifacts can be found at `C:\Users\s4m7\AppData\Local\Temp\cargo-installTMkn8h`

Caused by:
  failed to select a version for the requirement `security-framework = "^0.1.13"`
  candidate versions found which didn't match: 2.8.1, 2.8.0, 2.7.0, ...
  location searched: crates.io index
  required by package `native-tls v0.1.3`
      ... which satisfies dependency `native-tls = "^0.1.3"` of package `reqwest v0.8.0`
      ... which satisfies dependency `reqwest = "^0.8"` of package `neo v0.3.1``

**Comment by azdle** [comment]
Thanks for the heads up. I've published v0.3.2 to crates with a whole mess of dependency updates. It should be buildable now.

Of course, let me know if you run into any more problems.

**Comment by samthurston** [comment]
new error! progress!

error: failed to compile `neo v0.3.2`, intermediate artifacts can be found at `C:\Users\s4m7\AppData\Local\Temp\cargo-installXLkvuw`

Caused by:
  failed to select a version for the requirement `clap = "^4"`
  candidate versions found which didn't match: 3.2.23, 3.2.22, 3.2.21, ...
  location searched: crates.io index
  required by package `neo v0.3.2`

**Comment by azdle** [comment]
Hmm, that's odd. Any chance you're on a rust version that's older than 1.60?

```
rustc -V
```

That's the only reason I can think of at the moment why cargo wouldn't let
you use a newer version of the clap crate.

**Comment by samthurston** [comment]
sure enough, i was on 1.59.  updated and the issue is resolved.
