### ISSUE TITLE
Error while uploading on Windows OS: "Could not downcast to &str, need to downcast to alloc::string::String"

### ISSUE THREAD

**Issue by pwlin** [azdle/neo#4]
Hi there! 
I have compiled the `neo` binary successfully on Windows OS, and there were no errors. 
But whenever I run `neo.exe upload [file_name]` I get the following error:

> thread 'main' panicked at src\main.rs:159:18:
Mismatch between definition and access of `FILE`. Could not downcast to &str, need to downcast to alloc::string::String

It refers to these lines:
> let file_str = matches
          .get_one::<&str>("FILE")

Is this because I am on Windows OS? What should I change `<&str>` into?

**Comment by azdle** [comment]
I've never tried running this on Windows (and don't have access to a windows system to test now), so being on windows could be the difference that is making it fail for you.

Can you try changing it to `get_one::<String>("FILE")` (and also  `get_one::<String>("PATH")` a couple lines down) and let me know if it works?

**Comment by pwlin** [comment]
> Can you try changing it to `get_one::<String>("FILE")` (and also `get_one::<String>("PATH")` a couple lines down) and let me know if it works?

That did the trick! I changed all the occurrences of `<&str>` to `<String>` in `main.rs`, recompiled the binary, and now  everything works at it should. My sincere gratitude.

**Comment by azdle** [comment]
Great! I'm going to look into why that's happening and figure out if that is the right permanent fix.
